### ISSUE TITLE
Action is using old version of node

### ISSUE THREAD

**Issue by mattias-hofvander** [SecureCodeWarrior/github-action-add-sarif-contextual-training#218]
When using the action you get the below message:
"The following actions uses node12 which is deprecated and will be forced to run on node16: SecureCodeWarrior/github-action-add-sarif-contextual-training@v1"

Could you please update to node16

Best regards,
Mattias

**Comment by whoissqr** [comment]
today, i see one additional warning message from Github actions:

"Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: SecureCodeWarrior/github-action-add-sarif-contextual-training@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.:"

**Comment by henriquevcosta** [comment]
I've opened #228, hopefully a maintainer will pick it up 👍

**Comment by cwong-scw** [comment]
Thanks for the PR!
